### ISSUE TITLE
The thin ring of EWL, changing PCB

### ISSUE THREAD

**Issue by peng831** [Aharoni-Lab/Miniscope-v4#25]
Hello there,
  We want to enlarge the thin ring of EWL, the original ring is difficult to assemble. Do you think any problems will occur? I am worried that this change will adversely affect the camera.
The change looks like this：
![ring](https://user-images.githubusercontent.com/53943194/108593734-6de38e00-73b0-11eb-9631-3d765575dcb0.JPG)

Sorry to ask this question repeatedly， I cancelled it for the first time.

**Comment by fnsangiul** [comment]
Unfortunately that bigger diameter is not going to work. Not only because it's not going to fit in the objective module, it also won't properly make contact with the EWL.

**Comment by peng831** [comment]
Why can't it contact EWL correctly? In my opinion, it is a wire connecting the liquid lens, just like the thick ring on the other side of the liquid lens (about 282°  ring). What we want to do is to replace 'the original thin ring' to 'the bigger ring',which is like the right side ring of the picture.

**Comment by peng831** [comment]
We have measured the size of the liquid lens; if a larger ring is used, the liquid lens can touch a larger area.

**Comment by fnsangiul** [comment]
Electrically there shouldn't be any problem, but mechanically the bigger ring won't fit in the objective module and when pushed inside it won't make contact. We had a similar issue while validating the design of the objective module.

**Comment by peng831** [comment]
We are more worried about the impact of electrical performance; we can slightly modify the objective lens module to adapt to the large ring, in order to better assemble the liquid lens. The radius of the red ring is 3.72mm, and the line width is 0.6mm; the radii of the two yellow rings are 3.3mm and 4.3mm respectively.

**Comment by fnsangiul** [comment]
I think that the easiest solution for you is to test your new design with the pads we left on the bottom on the PCB

![image](https://user-images.githubusercontent.com/45947951/108634446-7a0e3080-742e-11eb-9479-b0dcda987e5b.png)

[PCBway](https://www.pcbway.com/) has the capabilities to fabricate them. I hope this helps

**Comment by peng831** [comment]
It's a good idea. Thank you for your help.
