### ISSUE TITLE
KiCad file Miniscope-v4-Rigid-Flex-cache.lib is missing

### ISSUE THREAD

**Issue by alexanderwiller** [Aharoni-Lab/Miniscope-v4#32]
**Describe the bug**
The KiCad schematic cannot be loaded properly, as the cached library `Miniscope-v4-Rigid-Flex-cache.lib`, which contains some of the symbols used, is missing.

**To Reproduce**
1. Clone the repository.
2. Open the project with KiCad
3. Open the schematic

**Expected behavior**
The library is included in the repository. The schematic can be loaded properly.

**Screenshots**
![2023-01-11 12_10_16-Warning](https://user-images.githubusercontent.com/4669302/211793186-ab2753bd-c0a1-45a7-8f6d-884b9d5c6497.png)
![2023-01-11 12_11_22-Window](https://user-images.githubusercontent.com/4669302/211793190-ac2c3619-6f96-48c8-9f6b-9a3e5563d628.png)

**Additional context**
We would like to convert the Miniscope V4 PCB to KiCad V6, add an automation pipeline for production data export with KiBot and make some small improvements, e.g. add radii where the traces meet the EWL contact rings, to increase robustness. This is closely related to the same effort that we go to with the Miniscope-LFOV: https://github.com/Aharoni-Lab/Miniscope-LFOV/issues/3

**Comment by jonnew** [comment]
This was a major issue with older version of KiCAD. You will need to add the Aharoni Lab KiCAD lib (https://github.com/Aharoni-Lab/KiCad-Library) to KiCAD and format all your library paths to match wherever its trying to look for those missing symbols. Once you do this and then upgrade to V6 (or V7, RC candidate is now available). The symbols will be embedded in the schematic and this will no longer be an issue.

**Comment by alexanderwiller** [comment]
Thanks for the reply, unfortunately, the link does not work for me. Is this a public repository?

I count on the embedding feature, it is very useful for distribution of projects. This already worked well for the Miniscope-LFOV 👍 For that project, the rescue lib was present and I could delete it after the conversion.

KiCad 7 RC, I prefer to not use yet, as I don't know how well it will work with KiBot etc.

**Comment by jonnew** [comment]
Huh, it is private. I don't know why I'm a member in that case since I'm not in the lab. @daharoni why is the KiCAD lib private?

**Comment by daharoni** [comment]
Hi! I just made our Kicad Library public. We will also try to port our projects over to Kicad 6 along with better embedded library management when we have time.

**Comment by Ildaron** [comment]
Hi @jonnew  can you say help how to transfer  Aharoni Lab KiCAD lib (https://github.com/Aharoni-Lab/KiCad-Library) to my new kicad ? I indicated way

![kicad](https://github.com/user-attachments/assets/43a4be3f-1ba0-4e88-a279-c55520720159)

**Comment by Ildaron** [comment]
Fixed , just updated kicad to 8.0.8
